# Generated by Django 3.2.5 on 2021-08-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.IntegerField(null=True),
        ),
    ]
